Generate all client code using code-gen (#163)
* Generate client code using code-gen

The client code generation was unintentionally removed as part of #112
when switching to controller-gen, which meant that we no longer had clientset, informers and listers generated - only types deepcopy were considered.
The original issue #90 with code-generator is now fixed by ensuring the code-generator code is available in the vendor directory as described here: https://github.com/kubernetes/code-generator/issues/57#issuecomment-498310800

* Pin code-generator dependencies to same version

Pinned `k8s.io/code-generator`, `k8s.io/client-go` and `k8s.io/apimachinery` to `kubernetes-1.15.0-alpha.1` to satisfy compilation dependencies.

To avoid compilation issues such as these when generating clientset.
```
pkg/client/clientset/versioned/typed/cassandra/v1alpha1/cassandra_client.go:57:45:
scheme.Codecs.WithoutConversion undefined (type serializer.CodecFactory
has no field or method WithoutConversion)
```

```
../../../../../pkg/mod/k8s.io/client-go@v0.0.0-20190619194433-921a716ae8da/rest/watch/decoder.go:57:103:
undefined: watch.Bookmark
```

* Use a real version for controller-runtime

To avoid error when loading unknown go module version as it is
pulled from the cassandra-operator module

* Pin down client-go and dep version in dependent modules

* ./hack/update-go-mod.sh